spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
logging:
  level:
    root: INFO
    com.blog.demo: DEBUG  # 특정 패키지에 대해 DEBUG 레벨로 설정

  

