name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image with version tag
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-blog:$VERSION .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-blog:$VERSION

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pull Docker image
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-blog:$VERSION

      - name: Run Docker container
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker run --name myblog-server \
          -d \
          -p 8080:8080 \
          -e SPRING_PROFILES_ACTIVE=prod \
          ${{ secrets.DOCKER_USERNAME }}/my-blog:$VERSION

